Repository Yanabada/Yanabada_BE, pull requests merged in 2024-01, with the labels that each got.

#2 프로젝트 패키지 디렉토리 구조 설계
  src/main/java/kr/co/fastcampus/yanabada/YanabadaApplication.java
  src/main/java/kr/co/fastcampus/yanabada/common/baseentity/BaseEntity.java
  src/main/java/kr/co/fastcampus/yanabada/common/config/AppConfig.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/BaseException.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/CommonEntityNotFoundException.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/ResponseBody.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/Status.java
  src/main/java/kr/co/fastcampus/yanabada/domain/test/controller/TestController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/test/dto/TestInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/test/dto/TestSaveRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/test/entity/TestEntity.java
  src/main/java/kr/co/fastcampus/yanabada/domain/test/repository/TestRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/test/service/TestService.java
  src/test/java/kr/co/fastcampus/yanabada/YanabadaApplicationTests.java
Labels: enhancement

#3 Develop 프로젝트 패키지 디렉토리 구조 설계
  src/main/java/kr/co/fastcampus/yanabada/YanabadaApplication.java
  src/main/java/kr/co/fastcampus/yanabada/common/baseentity/BaseEntity.java
  src/main/java/kr/co/fastcampus/yanabada/common/config/AppConfig.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/BaseException.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/CommonEntityNotFoundException.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/ResponseBody.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/Status.java
  src/main/java/kr/co/fastcampus/yanabada/domain/test/controller/TestController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/test/dto/TestInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/test/dto/TestSaveRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/test/entity/TestEntity.java
  src/main/java/kr/co/fastcampus/yanabada/domain/test/repository/TestRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/test/service/TestService.java
  src/test/java/kr/co/fastcampus/yanabada/YanabadaApplicationTests.java
Labels: enhancement

#7 숙소, 객실, 예약 Entity 설계
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/entity/Accommodation.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/entity/AccommodationOption.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/entity/Room.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/entity/RoomOption.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/entity/enums/Category.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/entity/enums/Region.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/entity/Member.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/entity/RoomOrder.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/entity/enums/OrderStatus.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/entity/enums/PaymentType.java
Labels: enhancement

#11 숙박, 객실, 주문 등록 API 구현
  build.gradle
  src/main/java/kr/co/fastcampus/yanabada/common/exception/AccommodationNotFoundException.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/CommonEntityNotFoundException.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/MemberNotFoundException.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/RoomNotFoundException.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/controller/AccommodationController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/dto/request/AccommodationSaveRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/dto/request/RoomSaveRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/repository/RoomRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/service/AccommodationService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/entity/Member.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/repository/MemberRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/controller/OrderController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/dto/request/OrderSaveRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/repository/OrderRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/service/OrderService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: enhancement

#12 상품 Entity 구현
  src/main/java/kr/co/fastcampus/yanabada/domain/product/entity/Product.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/entity/enums/ProductStatus.java
Labels: enhancement

#16 숙박 옵션 등록, 객실 옵셥 등록 API 구현
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/controller/AccommodationController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/dto/request/AccommodationOptionSaveRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/dto/request/RoomOptionSaveRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/dto/request/RoomSaveRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/entity/AccommodationOption.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/entity/Room.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/entity/RoomOption.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/entity/enums/Category.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/entity/enums/Region.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/repository/AccommodationOptionRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/repository/RoomOptionRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/repository/RoomRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/service/AccommodationService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/repository/MemberRepository.java
Labels: enhancement

#24 예약 Entity 수정 및 생성 API 수정
  src/main/java/kr/co/fastcampus/yanabada/common/utils/OrderCodeGenerator.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/dto/request/OrderSaveRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/entity/Order.java
Labels: enhancement

#21 Feature/13 스프링 시큐리티 및 JWT 적용
  build.gradle
  docker-compose.yml
  src/main/java/kr/co/fastcampus/yanabada/common/config/AppConfig.java
  src/main/java/kr/co/fastcampus/yanabada/common/config/RedisConfig.java
  src/main/java/kr/co/fastcampus/yanabada/common/config/SecurityConfig.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/ClaimParseFailedException.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/TokenExpiredException.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/TokenNotValidatedException.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/constant/JwtConstant.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/dto/TokenIssueResponse.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/filter/JwtAuthFilter.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/filter/JwtExceptionFilter.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/service/TokenService.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/util/JwtProvider.java
  src/main/java/kr/co/fastcampus/yanabada/common/redis/RedisUtils.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/yanabada/common/security/PrincipalDetails.java
  src/main/java/kr/co/fastcampus/yanabada/common/security/PrincipalDetailsService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/controller/AuthController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/dto/LoginRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/dto/SignUpRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/controller/MemberController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/entity/Member.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/entity/ProviderType.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/entity/RoleType.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/repository/MemberRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/service/MemberService.java
  src/main/resources/application.yml
Labels: enhancement

#22 상품 검색 API 구현
  .gitignore
  build.gradle
  src/main/java/kr/co/fastcampus/yanabada/common/config/QuerydslConfig.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/DivideByZeroException.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/yanabada/common/utils/SalesPercentageCalculator.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/controller/ProductController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/dto/request/ProductSearchRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/dto/request/enums/ProductSearchCategory.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/dto/request/enums/ProductSearchOption.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/dto/request/enums/ProductSearchOrderCondition.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/dto/response/ProductSummaryPageResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/dto/response/ProductSummaryResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/repository/ProductRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/service/ProductService.java
Labels: enhancement

#26 판매 가능 예약 내역 조회 API 구현
  src/main/java/kr/co/fastcampus/yanabada/common/exception/RandomCodeLengthRangeException.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/yanabada/common/utils/OrderCodeGenerator.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/controller/OrderController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/dto/response/OrderSummaryResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/repository/OrderRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/service/OrderService.java
Labels: enhancement

#20 Feature/14 예약내역 상세 API 구현
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/dto/response/RoomOptionResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/entity/Member.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/controller/OrderController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/dto/response/OrderInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/service/OrderService.java
  src/main/resources/application.yml
Labels: enhancement

#35 채팅방, 채팅 메세지 엔티티 설계
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/entity/ChatMessage.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/entity/ChatRoom.java
Labels: enhancement

#33 상품 상세 조회 API 구현
  src/main/java/kr/co/fastcampus/yanabada/common/exception/ProductNotFoundException.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/dto/response/AccommodationInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/dto/response/AccommodationOptionInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/dto/response/RoomInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/dto/response/RoomOptionInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/dto/response/MemberSummaryResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/controller/ProductController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/dto/response/ProductInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/repository/ProductRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/service/ProductService.java
Labels: enhancement

#30 토큰 Redis 저장 방식 변경
  docker-compose.yml
  src/main/java/kr/co/fastcampus/yanabada/common/config/RedisConfig.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/TokenNotExistAtCacheException.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/dto/TokenExpiredResponse.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/dto/TokenIssueResponse.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/dto/TokenRefreshResponse.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/filter/JwtAuthFilter.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/filter/JwtExceptionFilter.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/service/TokenService.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/util/JwtProvider.java
  src/main/java/kr/co/fastcampus/yanabada/common/redis/RedisUtils.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/controller/AuthController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/controller/MemberController.java
  src/main/resources/application.yml
Labels: enhancement

#46 멘토님 리뷰를 위한 리드미 작성
  README.md
Labels: documentation

#38 상품 판매 기한 종료 후 자동 취소 기능 구현
  src/main/java/kr/co/fastcampus/yanabada/YanabadaApplication.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/OrderNotFoundException.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/entity/Order.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/entity/enums/OrderStatus.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/service/OrderService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/entity/Product.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/service/ProductService.java
Labels: enhancement

#43 마이페이지 API 구현 및 이메일 인증 구현
  build.gradle
  src/main/java/kr/co/fastcampus/yanabada/common/config/EmailConfig.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/EmailSendFailedException.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/filter/JwtAuthFilter.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/util/JwtUtils.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/yanabada/common/security/PrincipalDetails.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/controller/AuthController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/dto/request/EmailAuthCodeRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/dto/request/LoginRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/dto/request/SignUpRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/dto/response/EmailAuthCodeResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/MailAuthService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/controller/MemberController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/dto/request/EmailDuplCheckRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/dto/request/ImgUrlModifyRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/dto/request/NickNameDuplCheckRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/dto/request/NickNameModifyRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/dto/request/PasswordModifyRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/dto/request/PhoneNumberModifyRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/dto/response/DuplCheckResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/entity/Member.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/repository/MemberRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/service/MemberService.java
  src/main/resources/application.yml
Labels: enhancement

#42 상품 수정 API 구현
  src/main/java/kr/co/fastcampus/yanabada/common/exception/InvalidStatusProductUpdateException.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/controller/AuthController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/repository/OrderRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/repository/OrderRepositoryCustom.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/repository/OrderRepositoryCustomImpl.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/service/OrderService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/controller/ProductController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/dto/request/ProductPatchRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/entity/Product.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/service/ProductService.java
Labels: enhancement

#50 상품 검색 응답 DTO 수정 및 객실 취소 정책 구현
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/dto/request/RoomSaveRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/dto/response/RoomInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/dto/response/RoomOptionResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/entity/Room.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/entity/enums/RoomCancelPolicy.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/dto/response/OrderInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/dto/response/ProductSummaryResponse.java
Labels: enhancement

#52 채팅방 등록 API 구현
  src/main/java/kr/co/fastcampus/yanabada/common/exception/CannotNegotiateOwnProductException.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/NegotiationNotPossibleException.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/yanabada/common/utils/EntityCodeGenerator.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/controller/ChatController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/dto/request/ChatRoomSaveRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/dto/response/ChatRoomInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/entity/ChatRoom.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/repository/ChatMessageRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/repository/ChatRoomRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/service/ChatService.java
Labels: enhancement

#53 채팅방 목록 조회 API 구현
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/controller/ChatController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/dto/response/ChatRoomSummaryResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/repository/ChatRoomRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/service/ChatService.java
Labels: enhancement

#55 채팅방 상세조회 (채팅내역 조회) API 구현
  src/main/java/kr/co/fastcampus/yanabada/common/exception/ChatRoomNotFoundException.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/IncorrectChatRoomMember.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/controller/ChatController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/dto/response/ChatMessageInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/dto/response/ChatRoomSummaryResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/repository/ChatRoomRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/service/ChatService.java
Labels: enhancement

#57 채팅방 수정(판매자 또는 구매자 마지막 확인 시간 수정) 및 삭제 API 구현
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/controller/ChatController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/dto/request/ChatRoomModifyRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/dto/response/ChatRoomModifyResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/entity/ChatRoom.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/service/ChatService.java
Labels: enhancement

#62 채팅 메세지 송/수신 API 구현
  build.gradle
  src/main/java/kr/co/fastcampus/yanabada/common/config/WebSockConfig.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/controller/ChatController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/dto/ReceivedChatMessage.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/dto/SendChatMessage.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/dto/response/ChatMessageInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/dto/response/ChatRoomModifyResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/dto/response/ChatRoomSummaryResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/service/ChatService.java
Labels: enhancement

#59 refactor: 상품 상세 응답 DTO 수정
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/dto/response/RoomInfoResponse.java
Labels: refactor

#67 야놀자 페이 entity 생성
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/entity/YanoljaPay.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/entity/YanoljaPayHistory.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/entity/enums/TransactionType.java
Labels: duplicate

#79 상품 상태 리팩토링
  src/main/java/kr/co/fastcampus/yanabada/domain/order/repository/OrderRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/entity/Product.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/entity/enums/ProductStatus.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/service/ProductService.java
Labels: refactor

#70 채팅 도메인 리팩토링
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/controller/ChatController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/dto/response/ChatMessageInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/dto/response/ChatMessagePageResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/entity/ChatRoom.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/repository/ChatMessageRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/service/ChatService.java
  src/main/resources/application.yml
Labels: refactor

#85 거래 내역 상세 조회 및 삭제 API 구현
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/controller/TradeController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/response/ApprovalTradeInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/response/PurchaseTradeInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/entity/Trade.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/service/TradeService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/dto/response/ProductInfoResponse.java
Labels: enhancement

#76 야놀자 페이 내역조회 구현
  src/main/java/kr/co/fastcampus/yanabada/common/exception/YanoljaPayNotFoundException.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/controller/YanoljaPayController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/response/PaymentHistoryResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/response/YanoljaPayHomeResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/entity/YanoljaPay.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/entity/enums/TransactionType.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/repository/YanoljaPayRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/service/YanoljaPayService.java
Labels: enhancement

#80 AdminPayment 엔티티 설계
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/entity/AdminPayment.java
Labels: enhancement

#90 [Refactor]일반 로그인 시 Member정보 응답 추가
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/controller/AuthController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/dto/response/LoginResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
Labels: refactor

#97 Room 엔티티 수정 및 각 도메인 ENUM 수정
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/dto/request/RoomSaveRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/dto/response/RoomInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/entity/Room.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/entity/enums/Category.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/entity/enums/PaymentType.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/dto/request/enums/ProductSearchCategory.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/kr/co/fastcampus/yanabada/domain/test/controller/TestController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/test/dto/TestInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/test/dto/TestSaveRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/test/entity/TestEntity.java
  src/main/java/kr/co/fastcampus/yanabada/domain/test/repository/TestRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/test/service/TestService.java
Labels: refactor

#91 [Refactor] 멤버 필드 수정
  src/main/java/kr/co/fastcampus/yanabada/common/security/PrincipalDetails.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/dto/request/OauthSignUpRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/dto/request/SignUpRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/entity/Member.java
Labels: refactor

#82 상품 status에 따른 판매 내역 조회 API 구현
  src/main/java/kr/co/fastcampus/yanabada/common/exception/UnavailableStatusQueryException.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/dto/request/OrderSaveRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/entity/Order.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/service/OrderService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/entity/Trade.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/repository/TradeRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/service/TradeService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/controller/ProductController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/dto/request/ProductSaveRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/dto/response/ProductHistoryInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/dto/response/ProductHistoryPageResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/entity/Product.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/repository/ProductRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/service/ProductService.java
Labels: enhancement, refactor

#89 구매 내역 조회 & 승인요청 내역 조회 API 구현
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/controller/TradeController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/response/ApprovalTradePageResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/response/ApprovalTradeSummaryResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/response/PurchaseTradePageResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/response/PurchaseTradeSummaryResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/entity/enums/TradeRole.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/repository/TradeRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/service/TradeService.java
Labels: enhancement

#92 결제 환불 로직 및 야놀자 페이 구현
  src/main/java/kr/co/fastcampus/yanabada/common/exception/DuplicateYanoljaPayException.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/IncorrectYanoljaPayPasswordException.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/NotEnoughPointException.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/NotEnoughYanoljaPayBalanceException.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/YanoljaPayHistoryNotFoundException.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/YanoljaPayNotFoundException.java
  src/main/java/kr/co/fastcampus/yanabada/common/firebase/dto/request/FcmMessageRequest.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/filter/JwtExceptionFilter.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/yanabada/common/security/oauth/Oauth2LoginFailureHandler.java
  src/main/java/kr/co/fastcampus/yanabada/common/security/oauth/Oauth2LoginSuccessHandler.java
  src/main/java/kr/co/fastcampus/yanabada/common/utils/AccountNumberSplitter.java
  src/main/java/kr/co/fastcampus/yanabada/common/utils/FeeCalculator.java
  src/main/java/kr/co/fastcampus/yanabada/common/utils/PayFeeCalculator.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/controller/MemberController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/entity/Member.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/controller/YanoljaPayController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/request/TradeSaveRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/request/YanoljaPayAmountRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/request/YanoljaPayHistorySearchRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/request/YanoljaPaySaveRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/response/PaymentHistoryResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/response/PurchaseTradeInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/response/YanoljaPayHistoryIdResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/response/YanoljaPayHistoryInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/response/YanoljaPayHistorySummaryPageResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/response/YanoljaPayHistorySummaryResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/response/YanoljaPayHomeResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/response/YanoljaPayInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/response/YanoljaPaySummaryResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/entity/YanoljaPay.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/entity/YanoljaPayHistory.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/entity/enums/ContentsType.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/entity/enums/TransactionType.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/repository/YanoljaPayHistoryRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/repository/YanoljaPayHistoryRepositoryCustom.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/repository/YanoljaPayHistoryRepositoryCustomImpl.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/service/TradeService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/service/YanoljaPayService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/service/ProductService.java
Labels: enhancement

#100 결제 및 환불 로직 리팩토링 및 어드민 페이의 누적 추가
  src/main/java/kr/co/fastcampus/yanabada/common/exception/AdminPaymentNotFoundException.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/entity/Member.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/request/YanoljaPayAmountRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/entity/AdminPayment.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/repository/AdminPaymentRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/service/TradeService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/service/ProductService.java
Labels: enhancement

#102 AdminPayment 누적 정보 조회 API 구현, 네이밍 리팩토링
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/controller/PaymentController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/dto/response/AdminPaymentInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/repository/AdminPaymentRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/service/PaymentService.java
Labels: enhancement, refactor

#107 알림 목록 조회 API 구현
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/controller/NotificationController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/dto/ChatNotificationDto.java
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/dto/response/NotificationInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/dto/response/NotificationPageResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/entity/NotificationHistory.java
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/repository/NotificationHistoryRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/service/NotificationService.java
Labels: enhancement

#108 로그인 기능 리팩토링
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/dto/SendChatMessage.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/dto/response/ChatMessageInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/dto/response/ChatRoomSummaryResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/controller/MemberController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/dto/request/ImgUrlModifyRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/dto/response/MemberDetailResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/dto/response/MemberSummaryResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/entity/Member.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/service/MemberService.java
Labels: refactor

#111 refactor: 시큐리티 허용 URL 변경
  src/main/java/kr/co/fastcampus/yanabada/common/config/SecurityConfig.java
Labels: refactor

#115 refactor: Security 관련 yml 환경 변수 분리
  src/main/java/kr/co/fastcampus/yanabada/common/config/EmailConfig.java
  src/main/java/kr/co/fastcampus/yanabada/common/config/SecurityConfig.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/NotMatchedProviderNameException.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/filter/JwtAuthFilter.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/yanabada/common/security/oauth/Oauth2Attribute.java
  src/main/java/kr/co/fastcampus/yanabada/common/security/oauth/Oauth2LoginFailureHandler.java
  src/main/java/kr/co/fastcampus/yanabada/common/security/oauth/Oauth2LoginSuccessHandler.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
  src/main/resources/application.yml
Labels: refactor

#112 알림 서비스 적용 및 Security 적용
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/dto/TradeNotificationDto.java
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/service/NotificationService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/controller/OrderController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/controller/PaymentController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/controller/TradeController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/service/TradeService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/service/ProductService.java
Labels: enhancement

#113 채팅 알림서비스 구현 및 시큐리티 적용
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/controller/ChatController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/service/ChatService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/dto/ChatNotificationDto.java
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/service/NotificationService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/controller/ProductController.java
Labels: enhancement, refactor

#116 야믈파일 리팩토링 및 알림처리 상수처리
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/service/NotificationService.java
  src/main/resources/application.yml
Labels: refactor

#98 develop 브랜치 자동 배포 스크립트 작성
  .github/workflows/cd-develop.yml
  build.gradle
Labels: ci/cd

#118 로그인 쿠키 적용
  src/main/java/kr/co/fastcampus/yanabada/common/security/oauth/Oauth2LoginSuccessHandler.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/controller/AuthController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
Labels: enhancement

#119 로그인 리팩토링
  src/main/java/kr/co/fastcampus/yanabada/common/exception/TokenCannotBeEmptyException.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/filter/JwtAuthFilter.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/filter/JwtExceptionFilter.java
  src/main/java/kr/co/fastcampus/yanabada/common/response/ErrorCode.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
Labels: refactor

#121 판매 가능한 예약 조회 로직 버그 수정
  src/main/java/kr/co/fastcampus/yanabada/domain/order/repository/OrderRepositoryCustomImpl.java
Labels: bug

#124 서버 시간대 서울 시간으로 변경
  src/main/java/kr/co/fastcampus/yanabada/YanabadaApplication.java
Labels: bug

#127 구매 내역 및 승인 요청 내역 조회 거래 status 구매자별 판매자별 구분 삭제
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/service/TradeService.java
Labels: bug

#131 이미지 필드 풀 URL 가질 수 있도록 리팩토링
  src/main/java/kr/co/fastcampus/yanabada/common/config/AppConfig.java
  src/main/java/kr/co/fastcampus/yanabada/common/utils/S3ImageUrlGenerator.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/dto/request/AccommodationSaveRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/dto/request/RoomSaveRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/service/AccommodationService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/service/NotificationService.java
  src/main/resources/application.yml
Labels: refactor

#132 상품 상세 조회, 예약 내역 상세 조회 API 응답 DTO 수정
  src/main/java/kr/co/fastcampus/yanabada/domain/order/dto/response/OrderInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/dto/response/ProductInfoResponse.java
Labels: refactor

#134 회원가입시 응답 DTO 리팩토링 및 잘못된 경로시 예외 처리 추가
  src/main/java/kr/co/fastcampus/yanabada/common/config/AppConfig.java
  src/main/java/kr/co/fastcampus/yanabada/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/controller/AuthController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/dto/response/SignUpResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
  src/main/resources/application.yml
Labels: enhancement, refactor

#140 쿠키 Secure 설정
  src/main/java/kr/co/fastcampus/yanabada/common/security/oauth/Oauth2LoginFailureHandler.java
  src/main/java/kr/co/fastcampus/yanabada/common/security/oauth/Oauth2LoginSuccessHandler.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
  src/main/resources/application.yml
Labels: refactor

#139 회원 가입시 야놀자 페이 자동 생성 로직 추가
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/entity/YanoljaPay.java
Labels: enhancement

#143 refactor: Cookie 설정 domain추가
  src/main/java/kr/co/fastcampus/yanabada/common/security/oauth/Oauth2LoginSuccessHandler.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
  src/main/resources/application.yml
Labels: refactor

#141 알림 개별삭제 리팩토링 및 알림 전체 삭제 API 구현
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/controller/NotificationController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/dto/request/NotificationDeleteRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/dto/response/NotificationIdResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/repository/NotificationHistoryRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/service/NotificationService.java
Labels: enhancement, refactor

#144 만료된 알림 자동 삭제 기능 구현
  src/main/java/kr/co/fastcampus/yanabada/common/security/oauth/Oauth2LoginSuccessHandler.java
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/property/NotificationProperties.java
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/repository/NotificationHistoryRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/repository/NotificationHistoryRepositoryCustom.java
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/repository/NotificationHistoryRepositoryCustomImpl.java
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/service/NotificationService.java
Labels: enhancement

#147 Access Token 만료기간 수정(1 Day)
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/constant/JwtConstant.java
Labels: refactor

#149 bug: RedirectUrl 테스팅
  src/main/java/kr/co/fastcampus/yanabada/common/security/oauth/Oauth2LoginSuccessHandler.java
Labels: bug

#151 판매 가능한 예약 조회 로직 수정
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/entity/enums/RoomCancelPolicy.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/repository/OrderRepositoryCustomImpl.java
Labels: refactor

#155 쿠키 설정 변경 - httponly, domain OFF
  src/main/java/kr/co/fastcampus/yanabada/common/config/SecurityConfig.java
  src/main/java/kr/co/fastcampus/yanabada/common/config/WebConfig.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
Labels: refactor

#160 refacor: NotificationDTO 변경
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/dto/ChatNotificationDto.java
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/service/NotificationService.java
Labels: refactor

#162 쿠키 설정 변경
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/filter/JwtAuthenticationEntryPoint.java
  src/main/java/kr/co/fastcampus/yanabada/common/security/oauth/Oauth2UserService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
Labels: refactor

#166 fix: 시큐리티 permit path 수정
  src/main/java/kr/co/fastcampus/yanabada/common/config/SecurityConfig.java
  src/main/java/kr/co/fastcampus/yanabada/common/config/WebConfig.java
Labels: bug

#167 fix: 8081 킬 명령어 수정
  .github/workflows/cd-release.yml
Labels: bug

#168 시큐리티 허용 path 수정 및 안 쓰는 로그 제거
  .github/workflows/cd-release.yml
  src/main/java/kr/co/fastcampus/yanabada/common/config/SecurityConfig.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/filter/JwtAuthFilter.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/util/JwtProvider.java
Labels: bug

#169 develop 브랜치 release브랜치로 병합
  .github/workflows/cd-release.yml
  src/main/java/kr/co/fastcampus/yanabada/common/config/SecurityConfig.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/filter/JwtAuthFilter.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/util/JwtProvider.java
Labels: enhancement

#170 누적사용자 조회 url 시큐리티 허용
  src/main/java/kr/co/fastcampus/yanabada/common/config/SecurityConfig.java
Labels: bug

#171 develop 브랜치 -> release 브랜치 병합
  src/main/java/kr/co/fastcampus/yanabada/common/config/SecurityConfig.java
Labels: bug

#172 refactor: CookieUtil 분리 및 카카오 로그인 쿠키 저장
  src/main/java/kr/co/fastcampus/yanabada/common/security/oauth/Oauth2LoginSuccessHandler.java
  src/main/java/kr/co/fastcampus/yanabada/common/utils/CookieCreator.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/controller/AuthController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
Labels: refactor

#174 소셜 로그인 쿠키 설정
  src/main/java/kr/co/fastcampus/yanabada/common/security/oauth/Oauth2LoginSuccessHandler.java
  src/main/java/kr/co/fastcampus/yanabada/common/utils/CookieCreator.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/controller/AuthController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
Labels: refactor

#178 fix: yml파일 수정
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
  src/main/resources/application.yml
Labels: refactor

#180 fix: 쿠키 설정 Expire 추가
  src/main/java/kr/co/fastcampus/yanabada/common/utils/CookieCreator.java
Labels: bug

#187 FCM 토큰 등록하지 않은 사람에겐 FCM 알림 보내지 않음처리
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/service/NotificationService.java
Labels: bug

#188 Release 브랜치 병합
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/service/NotificationService.java
Labels: bug

#191 fcm 토큰 없는 사람은 알림 서비스 보내지 않음
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/service/NotificationService.java
Labels: bug

#192 Release 병합
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/service/NotificationService.java
Labels: bug

#200 버그 수정 : 삭제된 내역 조회 불가 및 채팅 메세지 정렬 순서 변경
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/service/ChatService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/repository/TradeRepository.java
Labels: bug

#201 Release 브랜치 병합
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/service/ChatService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/repository/TradeRepository.java
Labels: bug

#203 채팅 메세지 썸네일 메세지 변경
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/service/ChatService.java
Labels: bug

#204 Release 브랜치 병합
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/service/ChatService.java
Labels: bug

#198 fix: 카카오 로그인 성공 리다이렉트 url 수동 변경
  src/main/java/kr/co/fastcampus/yanabada/common/security/oauth/Oauth2LoginSuccessHandler.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/controller/AuthController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/member/service/MemberService.java
Labels: bug

#206 판매 가능한 예약 내역 확인 날짜 수정
  src/main/java/kr/co/fastcampus/yanabada/common/security/PrincipalDetails.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/entity/enums/RoomCancelPolicy.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/controller/OrderController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/service/OrderService.java
  src/test/java/kr/co/fastcampus/yanabada/common/config/QueryDslTestConfig.java
  src/test/java/kr/co/fastcampus/yanabada/common/security/WithMockMember.java
  src/test/java/kr/co/fastcampus/yanabada/common/security/WithMockMemberSecurityContextFactory.java
  src/test/java/kr/co/fastcampus/yanabada/domain/product/controller/ProductControllerTest.java
Labels: bug, test

#207 Release 병합
  src/main/java/kr/co/fastcampus/yanabada/common/security/PrincipalDetails.java
  src/main/java/kr/co/fastcampus/yanabada/domain/accommodation/entity/enums/RoomCancelPolicy.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/controller/OrderController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/service/OrderService.java
  src/test/java/kr/co/fastcampus/yanabada/common/config/QueryDslTestConfig.java
  src/test/java/kr/co/fastcampus/yanabada/common/security/WithMockMember.java
  src/test/java/kr/co/fastcampus/yanabada/common/security/WithMockMemberSecurityContextFactory.java
  src/test/java/kr/co/fastcampus/yanabada/domain/product/controller/ProductControllerTest.java
Labels: bug

#209 fix: 카카오 로그인 redirect URL 변경
  src/main/java/kr/co/fastcampus/yanabada/common/security/oauth/Oauth2LoginSuccessHandler.java
Labels: wontfix

#215 fix: 카카오 로그인 시 redirectUrl 수정
  src/main/java/kr/co/fastcampus/yanabada/common/security/oauth/Oauth2LoginSuccessHandler.java
  src/main/resources/application.yml
Labels: bug

#216 fix: 카카오 로그인 시 redirectUrl 수정
  src/main/java/kr/co/fastcampus/yanabada/common/security/oauth/Oauth2LoginSuccessHandler.java
  src/main/resources/application.yml
Labels: bug

#217 feat: 카카오 회원가입 후 로그인 시 홈화면으로 redirect 추가
  src/main/java/kr/co/fastcampus/yanabada/common/security/oauth/Oauth2LoginSuccessHandler.java
Labels: enhancement

#218 feat: 카카오 회원가입 후 로그인 시 홈화면으로 redirect 추가
  src/main/java/kr/co/fastcampus/yanabada/common/security/oauth/Oauth2LoginSuccessHandler.java
Labels: enhancement

#213 테스트 코드 유틸클래스 구현
  src/test/java/kr/co/fastcampus/yanabada/common/utils/TestUtils.java
Labels: test

#221 서버 시간 jar 파일 실행 때마다 KST로 설정
  .github/workflows/cd-develop.yml
  .github/workflows/cd-release.yml
Labels: bug

#222 Release 병합
  .github/workflows/cd-develop.yml
  .github/workflows/cd-release.yml
  src/test/java/kr/co/fastcampus/yanabada/common/utils/TestUtils.java
Labels: bug, test

#223 fix: 소셜 로그인 성공 시 쿠키 전달 값(isLoggedIn) 추가
  src/main/java/kr/co/fastcampus/yanabada/common/utils/CookieCreator.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
Labels: enhancement

#224 fix: 소셜 로그인 성공 시 쿠키 전달 값(isLoggedIn) 추가
  src/main/java/kr/co/fastcampus/yanabada/common/utils/CookieCreator.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
Labels: enhancement

#227 fix: 일반 로그인시에도 쿠키 값에 isLoggedIn 값 추가 전달
  src/main/java/kr/co/fastcampus/yanabada/common/utils/CookieCreator.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
Labels: enhancement

#228 fix: 일반 로그인시에도 쿠키 값에 isLoggedIn 값 추가 전달
  src/main/java/kr/co/fastcampus/yanabada/common/utils/CookieCreator.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
Labels: enhancement

#230 feat: 비밀번호 재설정을 위한 이메일 인증 코드 검증 추가
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/controller/AuthController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/MailAuthService.java
Labels: enhancement

#231 거래내역 삭제시 상품 또한 삭제하여 내역 안보이게 수정
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/service/TradeService.java
Labels: bug

#232 Release 브랜치 병합
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/service/TradeService.java
Labels: bug

#234 할인율 계산 로직 수정
  src/main/java/kr/co/fastcampus/yanabada/domain/product/dto/response/ProductInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/dto/response/ProductSummaryResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/repository/ProductRepositoryCustomImpl.java
Labels: bug

#236 Trade 도메인 분리
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/filter/JwtAuthFilter.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/entity/enums/TradeRole.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/service/ProductService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/controller/TradeController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/dto/request/TradeSaveRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/dto/response/ApprovalTradeInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/dto/response/ApprovalTradePageResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/dto/response/ApprovalTradeSummaryResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/dto/response/PurchaseTradeInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/dto/response/PurchaseTradePageResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/dto/response/PurchaseTradeSummaryResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/dto/response/TradeIdResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/entity/Trade.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/entity/enums/TradeRole.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/entity/enums/TradeStatus.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/repository/TradeRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/service/TradeService.java
Labels: refactor

#237 Release 브랜치 병합 - Trade 도메인 분리
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/filter/JwtAuthFilter.java
  src/main/java/kr/co/fastcampus/yanabada/domain/payment/entity/enums/TradeRole.java
  src/main/java/kr/co/fastcampus/yanabada/domain/product/service/ProductService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/controller/TradeController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/dto/request/TradeSaveRequest.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/dto/response/ApprovalTradeInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/dto/response/ApprovalTradePageResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/dto/response/ApprovalTradeSummaryResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/dto/response/PurchaseTradeInfoResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/dto/response/PurchaseTradePageResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/dto/response/PurchaseTradeSummaryResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/dto/response/TradeIdResponse.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/entity/Trade.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/entity/enums/TradeRole.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/entity/enums/TradeStatus.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/repository/TradeRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/service/TradeService.java
Labels: refactor

#238 거래 삭제시 판매 상품 내역에서도 안보이게끔 수정
  src/main/java/kr/co/fastcampus/yanabada/domain/product/repository/ProductRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/service/TradeService.java
Labels: bug

#239 Release 거래 삭제시 판매 상품 내역에서도 안보이게끔 수정
  src/main/java/kr/co/fastcampus/yanabada/domain/product/repository/ProductRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/trade/service/TradeService.java
Labels: bug

#175 회원가입시 더미 주문 데이터 생성
  src/main/java/kr/co/fastcampus/yanabada/common/utils/RandomNumberGenerator.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
Labels: enhancement

#240 Release 병합 - 회원가입시 더미 주문 데이터 2개 갖도록 수정
  src/main/java/kr/co/fastcampus/yanabada/common/utils/RandomNumberGenerator.java
  src/main/java/kr/co/fastcampus/yanabada/domain/auth/service/AuthService.java
Labels: enhancement, refactor

#241 fix: Fcm 메세지 전송 조건문 반대로 적용
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/service/NotificationService.java
Labels: bug

#242 fix: Fcm 메세지 전송 조건문 반대로 적용
  src/main/java/kr/co/fastcampus/yanabada/domain/notification/service/NotificationService.java
Labels: bug

#244 리드미 작성
  README.md
  image/Yanabada-ERD.png
  image/데일리 스크럼.png
  image/백엔드 인프라 아키텍처.jpg
  image/소개이미지.png
  image/파이널 api 명세서.png
  image/프로젝트 파이프라인.jpg
Labels: documentation

#250 fix: JwtAuthFilter MemberRepository 의존성 제거
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/filter/JwtAuthFilter.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/util/JwtProvider.java
Labels: refactor

#251 Security AuthFilter에서 MemberRepository 의존성 제거
  README.md
  image/Yanabada-ERD.png
  image/데일리 스크럼.png
  image/백엔드 인프라 아키텍처.jpg
  image/소개이미지.png
  image/파이널 api 명세서.png
  image/프로젝트 파이프라인.jpg
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/filter/JwtAuthFilter.java
  src/main/java/kr/co/fastcampus/yanabada/common/jwt/util/JwtProvider.java
Labels: refactor

#245 리드미 추가 작성(이슈 및 회고)
  README.md
Labels: documentation

#254 리드미 수정 및 이슈 추가 작성
  README.md
  image/BE참고자료.png
  image/파이널 BE 회의록.png
  image/파이널_전체회의.png
Labels: documentation

#253 채팅 도메인 테스트 코드 작성 및 테스트 코드 유틸리티 클래스 구현
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/controller/ChatController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/repository/ChatRoomRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/service/ChatService.java
  src/test/java/kr/co/fastcampus/yanabada/common/utils/ApiTest.java
  src/test/java/kr/co/fastcampus/yanabada/common/utils/DatabaseCleaner.java
  src/test/java/kr/co/fastcampus/yanabada/common/utils/DatabaseClearExtension.java
  src/test/java/kr/co/fastcampus/yanabada/common/utils/TestUtils.java
  src/test/java/kr/co/fastcampus/yanabada/domain/chat/service/ChatServiceTest.java
  src/test/java/kr/co/fastcampus/yanabada/domain/chat/service/controller/ChatControllerTest.java
Labels: test

#257 README 에 회고 작성
  README.md
Labels: documentation

#258 ReadMe회고 작성
  README.md
Labels: documentation
