Repository Yanabada/Yanabada_BE, pull requests merged in 2024-02, with the labels that each got.

#259 Update README.md 회고
  README.md
Labels: documentation

#247 예약 관련 테스트 코드 작성
  src/main/java/kr/co/fastcampus/yanabada/domain/order/controller/OrderController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/service/OrderService.java
  src/test/java/kr/co/fastcampus/yanabada/common/utils/ApiTest.java
  src/test/java/kr/co/fastcampus/yanabada/common/utils/TestUtils.java
  src/test/java/kr/co/fastcampus/yanabada/domain/order/controller/OrderControllerTest.java
  src/test/java/kr/co/fastcampus/yanabada/domain/order/service/OrderServiceTest.java
Labels: refactor, test

#249 상품 관련 테스트 코드 작성
  src/test/java/kr/co/fastcampus/yanabada/domain/product/controller/ProductControllerTest.java
  src/test/java/kr/co/fastcampus/yanabada/domain/product/service/ProductServiceTest.java
Labels: test

#256 멤버 관련 테스트 코드 작성
  src/test/java/kr/co/fastcampus/yanabada/common/security/WithMockMemberSecurityContextFactory.java
  src/test/java/kr/co/fastcampus/yanabada/common/utils/TestUtils.java
  src/test/java/kr/co/fastcampus/yanabada/domain/member/controller/MemberControllerTest.java
  src/test/java/kr/co/fastcampus/yanabada/domain/member/service/MemberServiceTest.java
Labels: test

#260 Release 브랜치 병합(리드미 작성, 테스트 코드)
  README.md
  image/BE참고자료.png
  image/파이널 BE 회의록.png
  image/파이널_전체회의.png
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/controller/ChatController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/repository/ChatRoomRepository.java
  src/main/java/kr/co/fastcampus/yanabada/domain/chat/service/ChatService.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/controller/OrderController.java
  src/main/java/kr/co/fastcampus/yanabada/domain/order/service/OrderService.java
  src/test/java/kr/co/fastcampus/yanabada/common/security/WithMockMemberSecurityContextFactory.java
  src/test/java/kr/co/fastcampus/yanabada/common/utils/ApiTest.java
  src/test/java/kr/co/fastcampus/yanabada/common/utils/DatabaseCleaner.java
  src/test/java/kr/co/fastcampus/yanabada/common/utils/DatabaseClearExtension.java
  src/test/java/kr/co/fastcampus/yanabada/common/utils/TestUtils.java
  src/test/java/kr/co/fastcampus/yanabada/domain/chat/service/ChatServiceTest.java
  src/test/java/kr/co/fastcampus/yanabada/domain/chat/service/controller/ChatControllerTest.java
  src/test/java/kr/co/fastcampus/yanabada/domain/member/controller/MemberControllerTest.java
  src/test/java/kr/co/fastcampus/yanabada/domain/member/service/MemberServiceTest.java
  src/test/java/kr/co/fastcampus/yanabada/domain/order/controller/OrderControllerTest.java
  src/test/java/kr/co/fastcampus/yanabada/domain/order/service/OrderServiceTest.java
  src/test/java/kr/co/fastcampus/yanabada/domain/product/controller/ProductControllerTest.java
  src/test/java/kr/co/fastcampus/yanabada/domain/product/service/ProductServiceTest.java
Labels: documentation, test

#262 Release 브랜치에 수정사항 병합
  README.md
  src/test/java/kr/co/fastcampus/yanabada/domain/chat/controller/ChatControllerTest.java
Labels: documentation

#263 Main 브랜치 수정사항 병합
  README.md
  src/test/java/kr/co/fastcampus/yanabada/domain/chat/controller/ChatControllerTest.java
Labels: documentation

#264 Develop 수정사항 Release 병합
  README.md
  image/우수그룹1.png
  image/우수그릅2.png
Labels: documentation

#265 Release 수정사항 Main 병합
  README.md
  image/우수그룹1.png
  image/우수그릅2.png
Labels: documentation
